server:
  port: 8032
spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/harshaldb?useSSL=false
    username: harshalpandit95
    password: harshal123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: database-service
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8302/eureka
#  instance:
#    hostname: localhost